#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KantinPro.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KantinPro")]
	public partial class KantinProDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertISLEMLER(ISLEMLER instance);
    partial void UpdateISLEMLER(ISLEMLER instance);
    partial void DeleteISLEMLER(ISLEMLER instance);
    partial void InsertKATEGORILER(KATEGORILER instance);
    partial void UpdateKATEGORILER(KATEGORILER instance);
    partial void DeleteKATEGORILER(KATEGORILER instance);
    partial void InsertKULLANICILAR(KULLANICILAR instance);
    partial void UpdateKULLANICILAR(KULLANICILAR instance);
    partial void DeleteKULLANICILAR(KULLANICILAR instance);
    partial void InsertOGRENCILER(OGRENCILER instance);
    partial void UpdateOGRENCILER(OGRENCILER instance);
    partial void DeleteOGRENCILER(OGRENCILER instance);
    partial void InsertURUNLER(URUNLER instance);
    partial void UpdateURUNLER(URUNLER instance);
    partial void DeleteURUNLER(URUNLER instance);
    #endregion
		
		public KantinProDataContext() : 
				base(global::KantinPro.Properties.Settings.Default.KantinProConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public KantinProDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KantinProDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KantinProDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KantinProDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ISLEMLER> ISLEMLER
		{
			get
			{
				return this.GetTable<ISLEMLER>();
			}
		}
		
		public System.Data.Linq.Table<KATEGORILER> KATEGORILER
		{
			get
			{
				return this.GetTable<KATEGORILER>();
			}
		}
		
		public System.Data.Linq.Table<KULLANICILAR> KULLANICILAR
		{
			get
			{
				return this.GetTable<KULLANICILAR>();
			}
		}
		
		public System.Data.Linq.Table<OGRENCILER> OGRENCILER
		{
			get
			{
				return this.GetTable<OGRENCILER>();
			}
		}
		
		public System.Data.Linq.Table<URUNLER> URUNLER
		{
			get
			{
				return this.GetTable<URUNLER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ISLEMLER")]
	public partial class ISLEMLER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _ISLEM_YAPAN_ID;
		
		private int _OGRENCI_ID;
		
		private int _URUN_ID;
		
		private int _ADET;
		
		private decimal _TOPLAM;
		
		private System.DateTime _ISLEM_TARIHI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnISLEM_YAPAN_IDChanging(int value);
    partial void OnISLEM_YAPAN_IDChanged();
    partial void OnOGRENCI_IDChanging(int value);
    partial void OnOGRENCI_IDChanged();
    partial void OnURUN_IDChanging(int value);
    partial void OnURUN_IDChanged();
    partial void OnADETChanging(int value);
    partial void OnADETChanged();
    partial void OnTOPLAMChanging(decimal value);
    partial void OnTOPLAMChanged();
    partial void OnISLEM_TARIHIChanging(System.DateTime value);
    partial void OnISLEM_TARIHIChanged();
    #endregion
		
		public ISLEMLER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISLEM_YAPAN_ID", DbType="Int NOT NULL")]
		public int ISLEM_YAPAN_ID
		{
			get
			{
				return this._ISLEM_YAPAN_ID;
			}
			set
			{
				if ((this._ISLEM_YAPAN_ID != value))
				{
					this.OnISLEM_YAPAN_IDChanging(value);
					this.SendPropertyChanging();
					this._ISLEM_YAPAN_ID = value;
					this.SendPropertyChanged("ISLEM_YAPAN_ID");
					this.OnISLEM_YAPAN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OGRENCI_ID", DbType="Int NOT NULL")]
		public int OGRENCI_ID
		{
			get
			{
				return this._OGRENCI_ID;
			}
			set
			{
				if ((this._OGRENCI_ID != value))
				{
					this.OnOGRENCI_IDChanging(value);
					this.SendPropertyChanging();
					this._OGRENCI_ID = value;
					this.SendPropertyChanged("OGRENCI_ID");
					this.OnOGRENCI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URUN_ID", DbType="Int NOT NULL")]
		public int URUN_ID
		{
			get
			{
				return this._URUN_ID;
			}
			set
			{
				if ((this._URUN_ID != value))
				{
					this.OnURUN_IDChanging(value);
					this.SendPropertyChanging();
					this._URUN_ID = value;
					this.SendPropertyChanged("URUN_ID");
					this.OnURUN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADET", DbType="Int NOT NULL")]
		public int ADET
		{
			get
			{
				return this._ADET;
			}
			set
			{
				if ((this._ADET != value))
				{
					this.OnADETChanging(value);
					this.SendPropertyChanging();
					this._ADET = value;
					this.SendPropertyChanged("ADET");
					this.OnADETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOPLAM", DbType="Money NOT NULL")]
		public decimal TOPLAM
		{
			get
			{
				return this._TOPLAM;
			}
			set
			{
				if ((this._TOPLAM != value))
				{
					this.OnTOPLAMChanging(value);
					this.SendPropertyChanging();
					this._TOPLAM = value;
					this.SendPropertyChanged("TOPLAM");
					this.OnTOPLAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISLEM_TARIHI", DbType="DateTime NOT NULL")]
		public System.DateTime ISLEM_TARIHI
		{
			get
			{
				return this._ISLEM_TARIHI;
			}
			set
			{
				if ((this._ISLEM_TARIHI != value))
				{
					this.OnISLEM_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._ISLEM_TARIHI = value;
					this.SendPropertyChanged("ISLEM_TARIHI");
					this.OnISLEM_TARIHIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KATEGORILER")]
	public partial class KATEGORILER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _KATEGORI_ADI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKATEGORI_ADIChanging(string value);
    partial void OnKATEGORI_ADIChanged();
    #endregion
		
		public KATEGORILER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KATEGORI_ADI", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string KATEGORI_ADI
		{
			get
			{
				return this._KATEGORI_ADI;
			}
			set
			{
				if ((this._KATEGORI_ADI != value))
				{
					this.OnKATEGORI_ADIChanging(value);
					this.SendPropertyChanging();
					this._KATEGORI_ADI = value;
					this.SendPropertyChanged("KATEGORI_ADI");
					this.OnKATEGORI_ADIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KULLANICILAR")]
	public partial class KULLANICILAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _USERNAME;
		
		private string _PASSWORD;
		
		private int _YETKI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnPASSWORDChanging(string value);
    partial void OnPASSWORDChanged();
    partial void OnYETKIChanging(int value);
    partial void OnYETKIChanged();
    #endregion
		
		public KULLANICILAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORD", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string PASSWORD
		{
			get
			{
				return this._PASSWORD;
			}
			set
			{
				if ((this._PASSWORD != value))
				{
					this.OnPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._PASSWORD = value;
					this.SendPropertyChanged("PASSWORD");
					this.OnPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKI", DbType="Int NOT NULL")]
		public int YETKI
		{
			get
			{
				return this._YETKI;
			}
			set
			{
				if ((this._YETKI != value))
				{
					this.OnYETKIChanging(value);
					this.SendPropertyChanging();
					this._YETKI = value;
					this.SendPropertyChanged("YETKI");
					this.OnYETKIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OGRENCILER")]
	public partial class OGRENCILER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CARD_ID;
		
		private string _OGRENCI_ADI;
		
		private string _OGRENCI_SOYADI;
		
		private decimal _BAKIYE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCARD_IDChanging(string value);
    partial void OnCARD_IDChanged();
    partial void OnOGRENCI_ADIChanging(string value);
    partial void OnOGRENCI_ADIChanged();
    partial void OnOGRENCI_SOYADIChanging(string value);
    partial void OnOGRENCI_SOYADIChanged();
    partial void OnBAKIYEChanging(decimal value);
    partial void OnBAKIYEChanged();
    #endregion
		
		public OGRENCILER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARD_ID", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string CARD_ID
		{
			get
			{
				return this._CARD_ID;
			}
			set
			{
				if ((this._CARD_ID != value))
				{
					this.OnCARD_IDChanging(value);
					this.SendPropertyChanging();
					this._CARD_ID = value;
					this.SendPropertyChanged("CARD_ID");
					this.OnCARD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OGRENCI_ADI", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string OGRENCI_ADI
		{
			get
			{
				return this._OGRENCI_ADI;
			}
			set
			{
				if ((this._OGRENCI_ADI != value))
				{
					this.OnOGRENCI_ADIChanging(value);
					this.SendPropertyChanging();
					this._OGRENCI_ADI = value;
					this.SendPropertyChanged("OGRENCI_ADI");
					this.OnOGRENCI_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OGRENCI_SOYADI", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string OGRENCI_SOYADI
		{
			get
			{
				return this._OGRENCI_SOYADI;
			}
			set
			{
				if ((this._OGRENCI_SOYADI != value))
				{
					this.OnOGRENCI_SOYADIChanging(value);
					this.SendPropertyChanging();
					this._OGRENCI_SOYADI = value;
					this.SendPropertyChanged("OGRENCI_SOYADI");
					this.OnOGRENCI_SOYADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAKIYE", DbType="Money NOT NULL")]
		public decimal BAKIYE
		{
			get
			{
				return this._BAKIYE;
			}
			set
			{
				if ((this._BAKIYE != value))
				{
					this.OnBAKIYEChanging(value);
					this.SendPropertyChanging();
					this._BAKIYE = value;
					this.SendPropertyChanged("BAKIYE");
					this.OnBAKIYEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.URUNLER")]
	public partial class URUNLER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _KATEGORI_ID;
		
		private int _BARKOD_NO;
		
		private string _URUN_ADI;
		
		private decimal _BIRIM_FIYATI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnKATEGORI_IDChanging(int value);
    partial void OnKATEGORI_IDChanged();
    partial void OnBARKOD_NOChanging(int value);
    partial void OnBARKOD_NOChanged();
    partial void OnURUN_ADIChanging(string value);
    partial void OnURUN_ADIChanged();
    partial void OnBIRIM_FIYATIChanging(decimal value);
    partial void OnBIRIM_FIYATIChanged();
    #endregion
		
		public URUNLER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KATEGORI_ID", DbType="Int NOT NULL")]
		public int KATEGORI_ID
		{
			get
			{
				return this._KATEGORI_ID;
			}
			set
			{
				if ((this._KATEGORI_ID != value))
				{
					this.OnKATEGORI_IDChanging(value);
					this.SendPropertyChanging();
					this._KATEGORI_ID = value;
					this.SendPropertyChanged("KATEGORI_ID");
					this.OnKATEGORI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARKOD_NO", DbType="Int NOT NULL")]
		public int BARKOD_NO
		{
			get
			{
				return this._BARKOD_NO;
			}
			set
			{
				if ((this._BARKOD_NO != value))
				{
					this.OnBARKOD_NOChanging(value);
					this.SendPropertyChanging();
					this._BARKOD_NO = value;
					this.SendPropertyChanged("BARKOD_NO");
					this.OnBARKOD_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URUN_ADI", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string URUN_ADI
		{
			get
			{
				return this._URUN_ADI;
			}
			set
			{
				if ((this._URUN_ADI != value))
				{
					this.OnURUN_ADIChanging(value);
					this.SendPropertyChanging();
					this._URUN_ADI = value;
					this.SendPropertyChanged("URUN_ADI");
					this.OnURUN_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRIM_FIYATI", DbType="Money NOT NULL")]
		public decimal BIRIM_FIYATI
		{
			get
			{
				return this._BIRIM_FIYATI;
			}
			set
			{
				if ((this._BIRIM_FIYATI != value))
				{
					this.OnBIRIM_FIYATIChanging(value);
					this.SendPropertyChanging();
					this._BIRIM_FIYATI = value;
					this.SendPropertyChanged("BIRIM_FIYATI");
					this.OnBIRIM_FIYATIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
